//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRB {
	
	
	public partial class Login {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.Panel procesoStatusContainer;
		
		protected System.Web.UI.WebControls.Label procesoStatus;
		
		protected System.Web.UI.WebControls.TextBox txtLogin;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.HiddenField urlReferer;
	}
}
